grails-app/domain/bandstorm/Band.groovy
package bandstorm

/**
 * Represent a group of people (users and external real persons) in the scope of a band.
 * In the future this class could also represent a musical association from a town for instance.
 * */

class Band {
    String name
    Date dateCreated
    String description
    String address

    static hasMany = [tags : Tag]

    static constraints = {
        name blank:false,maxSize: 35, minSize: 3
        dateCreated date: true
        description blank: false,maxSize: 550
        address nullable: true, blank: true
    }
}

grails-app/controllers/bandstorm/BandController.groovy
package bandstorm

import bandstorm.service.UserService
import bandstorm.service.dao.BandDaoService
import bandstorm.service.dao.UserDaoService
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import org.springframework.security.authentication.AuthenticationManager
import org.springframework.security.core.context.SecurityContextHolder

import static org.springframework.http.HttpStatus.*

/**
 * Controller class for Bands
 */
@Secured(["ROLE_USER", "ROLE_ADMIN"])
@Transactional(readOnly = true)
class BandController {
    def springSecurityService
    UserService userService

    BandDaoService bandDaoService
    UserDaoService userDaoService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    AuthenticationManager authenticationManager

    /**
     * Show the list of the followed bands for current user.
     * @param max : max of displayed band in the page
     * @return List of bands
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.sort = "dateCreated"
        params.order = "desc"
        def calendar = Calendar.getInstance()
        calendar.set(2015,Calendar.SEPTEMBER, 01)
        Band band = new Band(name: "", description: "", address: "")
        respond Band.list(params), model: [bandInstance: band,bandInstanceCount: Band.count()]
    }

    /**
     * Show details for the selected band
     * @param bandInstance : selected band
     * @return band details
     */
    def show(Band bandInstance) {
        if(bandInstance == null) {
            return response.sendError(404)
        }

        respond bandInstance
    }

    /**
     * Create a band from the form
     * @return band instance
     */
    def create() {
        respond new Band(params)
    }

    /**
     * Save band from the form
     * @param bandInstance : selected band
     * @return band instance
     */
    @Transactional
    def save(Band bandInstance) {
        if (bandInstance == null) {
            notFound()
            return
        }

        try {
            bandInstance.name = params.bandName
            bandInstance.address = params.bandAddress
            bandInstance.description = params.bandDescription
            bandInstance.validate()
        } catch (Exception e) {
            e.printStackTrace()
            render template: 'form', model: [bandInstance: bandInstance, status: "KO"]
        }

        if (bandInstance.hasErrors()) {
            render template: 'form', model: [bandInstance: bandInstance, status: "KO"]
            return
        }

        try {
            if (params.bandTags) {
                def paramTags = params.bandTags.tokenize(';')
                bandInstance.tags = new ArrayList<Tag>()
                paramTags.eachWithIndex { item, index ->
                    def tag = new Tag(name: item).save()
                    bandInstance.tags.add(tag)
                }
            }
        } catch (Exception e) {
            e.printStackTrace()
        }

        try {
            User user = User.findByUsername(SecurityContextHolder.getContext().getAuthentication().getName())
            user.addToGroupsFollowed(bandInstance)
            userDaoService.update(user)
        }
        catch (AuthenticationException) {
        }


        bandDaoService.create(bandInstance)
        render template: 'form', model: [bandInstance: bandInstance, status: "OK"]


    }

    /**
     * Current user want to join a band
     * @param bandInstance
     */
    def join(Band bandInstance) {
        if(bandInstance == null) {
            return response.sendError(404)
        }

        try {
            User user = User.findByUsername(userService.springSecurityService.getCurrentUser())
            bandDaoService.joinBand(user, bandInstance)
        } catch (AuthenticationException) {
        }

        redirect action: 'home', controller: 'user', namespace: null
    }

    /**
     * Edit a band instance
     * @param bandInstance: selected band
     * @return a band instance
     */
    def edit(Band bandInstance) {
        respond bandInstance
    }

    /**
     * Update a band instance
     * @param bandInstance: band instance to update
     * @return band instance
     */
    @Transactional
    def update(Band bandInstance) {
        if (bandInstance == null) {
            notFound()
            return
        }

        if (bandInstance.hasErrors()) {
            respond bandInstance.errors, view: 'edit'
            return
        }

        bandInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Band.label', default: 'Band'), bandInstance.id])
                redirect bandInstance
            }
            '*' { respond bandInstance, [status: OK] }
        }
    }

    /**
     * Delete a band
     * @param bandInstance : band to delete
     * @return if the band is deleted
     */
    @Transactional
    def delete(Band bandInstance) {

        if (bandInstance == null) {
            notFound()
            return
        }

        bandInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'band.label', default: 'Band'), bandInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    /**
     * Show an error page, if not found.
     */
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'band.label', default: 'Band'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/band/_display-band.gsp
<dl class="dl-horizontal">
    <g:if test="${bandInstance?.name}">
        <dt>Nom</dt>
        <dd><g:fieldValue bean="${bandInstance}" field="name"/></dd>
    </g:if>

    <g:if test="${bandInstance?.dateCreated}">
        <dt>Date de création</dt>
        <dd><g:fieldValue bean="${bandInstance}" field="dateCreated"/></dd>
    </g:if>

    <g:if test="${bandInstance?.address}">
        <dt>Lieu</dt>
        <dd><g:fieldValue bean="${bandInstance}" field="address"/></dd>
    </g:if>

    <g:if test="${bandInstance?.description}">
        <dt>Description</dt>
        <dd><g:fieldValue bean="${bandInstance}" field="description"/></dd>
    </g:if>

</dl>

grails-app/views/band/_form.gsp
<%@ page import="bandstorm.Band" %>

<div class="form-group">
	<div class="row">
		<div class="col-md-6">
			<label for="bandName">Nom</label>
			<g:textField name="bandName" class="form-control" maxlength="35" id="bandName" placeholder="Nom"
						 value="${bandInstance?.name}"/>
			<g:hasErrors bean="${bandInstance}" field="name">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<strong>Le nom doit être compris entre 3 et 35 caractères</strong>
				</div>
			</g:hasErrors>
		</div>
	</div>
</div>

<div class="form-group">
	<label for="bandAddress">Lieu</label>
	<g:textField name="bandAddress" class="form-control"
				 maxlength="200" id="bandAddress" placeholder="Souhaitez vous indiquer un pays/ville d'appartenance ?" value="${bandInstance?.address}"/>
	<g:hasErrors bean="${bandInstance}" field="address">

		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
					aria-hidden="true">&times;</span></button>
		</div>
	</g:hasErrors>
</div>

<div class="form-group">
	<label for="bandDescription">Description</label>
	<g:textArea rows="5" name="bandDescription" class="form-control" id="bandDescription" placeholder="Décrivez votre groupe" value="${bandInstance?.description}"/>
	<g:hasErrors bean="${bandInstance}" field="description">
		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
					aria-hidden="true">&times;</span></button>
			<strong>La description du groupe est limitée ne peut être vide (limite 550 caractères).</strong>
		</div>
	</g:hasErrors>
</div>

<div class="form-group">
	<label for="bandTags">Tags</label>
	<g:textField name="bandTags" class="form-control" id="bandTags" placeholder="Ajoutez des tags en les séparant par un point-virgule"/>
</div>

<div>
	<h1 style="display: none" id="head">${(status) ? status :'empty'}</h1>
</div>

<g:submitToRemote class="btn btn-primary" url="[resource:bandInstance, controller:'band', action:'save']" update="creationForm" onSuccess="if(document.getElementById('head').innerHTML == 'OK'){swal({title:'Succès !',text: 'Votre groupe a été créée !',type: 'success'},function(){window.location.href = '${createLink(action: 'index')}';});}" value="Créer" />

grails-app/views/band/_modal.gsp
<!-- Modal -->
<div class="modal fade" id="myModal${bandInstance.id}" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Détail</h4>
            </div>
            <div class="modal-body">
                <g:render template="/band/display-band" model="[bandInstance:bandInstance]"></g:render>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <a href="${createLink(action: 'join',controller: 'band', id: bandInstance.id)}" class="btn btn-primary">Join band</button></a>

            </div>
        </div>
    </div>
</div>

grails-app/views/band/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'band.label', default: 'Band')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-band" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-band" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bandInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bandInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bandInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/band/edit.gsp
<%@ page import="bandstorm.Band" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'band.label', default: 'Band')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-band" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-band" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bandInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bandInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bandInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${bandInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/band/index.gsp
<%@ page import="bandstorm.Band" %>
<!DOCTYPE html>
<html>
	<head>
<meta name="layout" content="main">
<g:set var="entityName" value="${message(code: 'band.label', default: 'Band')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
<style>
.centered ul li {
    display: inline;
    margin: 3px;
}
.pagination {
    margin: 2px;
    box-sizing: border-box;
}

.prev, .next {
    border: solid 2px deepskyblue;
    background: whitesmoke;
    border-radius: 5px;
    padding: 4px;
    box-sizing: inherit;
}

.next {
    padding: 4.5px 10px 4.5px 10px;
}

.centered ul a {
    color: black;
    box-sizing: inherit;
}

.centered ul a:hover {
    text-decoration: none;
}

.alert {
    margin-top: 5px;
}

.tab-content {
    background-color: whitesmoke;
    padding: 10px;
    padding-top:30px ;
    margin-bottom: 30px;
}
</style>
</head>
</head>
<body>
<div class="container centered" style=" padding-top:30px;width: 90%; min-height: 300px; background-color: rgba(245,245,245,0.95);">
    <div class="container-fluid">
        <h2>Mes groupes</h2>
        <ul class="nav nav-tabs nav-justified">
            <li class="active"><a data-toggle="tab" href="#view">Liste de groupes</a></li>
            <li><a data-toggle="tab" href="#create">Créer un nouveau groupe</a></li>
        </ul>

        <div class="tab-content">
            <div id="view" class="tab-pane fade in active">
                <div class="table-responsive" id="listedBands">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Date de création</th>
                            <th>Lieu</th>
                            <th>Description</th>
                        </tr>
                        </thead>
                        <tbody>
                        <g:each in="${bandInstanceList}" var="bandInstance">
                            <tr>
                                <td><a type="button" data-toggle="modal" data-target="#myModal${bandInstance.id}">${fieldValue(bean: bandInstance, field: "name")}</a></td>
                                <g:render template="modal" model="[bandInstance: bandInstance]"></g:render>
                                <td><g:formatDate date="${bandInstance.dateCreated}" /></td>

                                <td>${fieldValue(bean: bandInstance, field: "address")}</td>

                                <td>${fieldValue(bean: bandInstance, field: "description")}</td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>

                    <g:paginate total="${bandInstanceCount?:0}" />

                </div>
            </div>
            <div id="create" class="tab-pane fade">
                <g:form >
                    <fieldset class="form" id="creationForm">
                        <g:render template="form" bean="${bandInstance}"/>
                    </fieldset>
                </g:form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/band/show.gsp
<%@ page import="bandstorm.Band" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<meta name="layout" content="main"/>



<div class="container" style="padding-top: 100px;">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 blog-main" style="background-color:rgb(255,255,255);padding:15px;margin-left: 10px;">
				<h2>${bandInstance?.name}</h2>
				<br>
				<div class="bs-example" data-example-id="media-alignment">
				<g:render template="/band/display-band" model="[bandInstance:bandInstance]"></g:render>
				</div>
			</div><!-- /.blog-userHomePage -->
		</div><!-- /.row -->
	</div>
</div>

</body>
</html>