grails-app/domain/bandstorm/User.groovy
package bandstorm
/**
 * Domain class that represents users,
 * and different event, lights and groups related
 * to them
 */
class User extends SecUser {

    String email
    String firstName
    String lastName
    Date birthDate
    String country
    Date dateCreated
    String urlAvatar

    static hasMany = [posts : Status, interests : Tag, participates : Event, manages : Event, groupsFollowed : Band ]


    static constraints = {
        username blank: false, nullable: false, minSize: 3
        email email : true, blank : false
        firstName blank: false, nullable: false
        lastName blank: false, nullable: false
        country blank: false, nullable: false
        birthDate max: new Date()
        posts nullable: true
        interests nullable: true
        participates nullable: true
        manages nullable: true
        groupsFollowed nullable: true
        urlAvatar blank: true, nullable: true, url: true, minSize   : 0
        password blank: false, nullable: false, minSize: 6
    }

    User(String username, String password, String email,
         String firstName, String lastName,
         Date birthDate, String country, String urlavatar) {
        super(username, password)
        this.email = email
        this.firstName = firstName
        this.lastName = lastName
        this.birthDate = birthDate
        this.country = country
        this.urlAvatar = urlAvatar;
    }

    transient userDaoService

    /**
     * Check if a follow relation exist between two users
     * @param follower User follower
     * @return true if relation exist else false
     */
    def isFollowed(User follower) {
        boolean res = false
        if(userDaoService.findFollowByFollowerAndFollowed(follower,this)){
            res = true
        }
        res
    }

    def isInBand(Band b) {
        return GroupMember.findByUserAndBand(this, b) != null
    }

    List<Band> getBands() {
        List<Band> ret = new ArrayList<>()

        GroupMember.findAllByUser(this).each {
            ret << it.band
        }

        return ret
    }
}

grails-app/controllers/bandstorm/UserController.groovy
package bandstorm

import bandstorm.service.LightService
import bandstorm.service.StatusService
import bandstorm.service.UserService
import bandstorm.service.dao.UserDaoService
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import org.springframework.security.authentication.AuthenticationManager
import org.springframework.security.core.context.SecurityContextHolder

import static org.springframework.http.HttpStatus.NOT_FOUND
import static org.springframework.http.HttpStatus.NO_CONTENT

/**
 * User controller class
 */
@Transactional(readOnly = true)
@Secured("permitAll")
class UserController {
    def springSecurityService
    StatusService statusService
    UserService userService
    UserDaoService userDaoService
    LightService lightService

    static allowedMethods = [save: "POST", update: "POST", delete: "DELETE"]

    /**
     * Retrun the list of user
     * @param max : max of user to show in the page
     * @return a list of user
     */
    @Secured(["ROLE_USER","ROLE_ADMIN"])
    def index(Integer max) {
        redirect action: 'home', controller: 'user', namespace: null
    }

    /**
     * Show the page of an user
     * @param userInstance : user object
     * @return details for the user and his news
     */
    @Secured(["ROLE_USER","ROLE_ADMIN"])
    def show(User userInstance) {
        if(userInstance == null) {
            return response.sendError(404)
        }
        
        def currentUser = springSecurityService.currentUser
        def statusList = statusService.getStatusOfUser(userInstance)
        respond userInstance, model: [currentUser: currentUser,
                                     statusList: statusList]
    }

    /**
     * Redirect to user home if connected
     * @return redirection to index or home
     */
    def urlRedirect() {
        if(userService.springSecurityService.isLoggedIn()) {
            redirect (action: "home")
        } else {
            redirect(uri: "/index")
        }
    }

    /**
     * Create an new user
     * @return a new user
     */
    def create() {
        respond new User(params)
    }

    /**
     * Activation of an user
     * @return the activation page
     */
    def activateAccount() {
        User userInstance = User.findByUsername(params.username)
        userService.setUserRole(userInstance)
        if(userService.springSecurityService.isLoggedIn()) {
            redirect(action: "logout")
        }
        render (view: "successCreation", model: [type: "activation"])
    }


    /**
     * The page for edition of a profil
     * @param userInstance : user object
     * @return form for user profil
     */
    @Secured(["ROLE_USER","ROLE_ADMIN"])
    def profilSettings(User userInstance) {
        if (userInstance == null) {
            userInstance = User.findByUsername(userService.springSecurityService.getCurrentUser())
        }
        respond userInstance
    }

    /**
     * Page for edition of the password
     * @param userInstance : user to edit
     * @return for for user password
     */
    @Secured(["ROLE_USER","ROLE_ADMIN"])
    def passwordSettings(User userInstance) {

        if (userInstance == null) {
            userInstance = userService.springSecurityService.getCurrentUser()
        }
        respond userInstance
    }

    /**
     * User homepage, show the news(status) of an user
     * @return the homepage of the user
     */
    def home() {
        if (!userService.springSecurityService.isLoggedIn()) {
            try {
                userService.logIn(params?.username, params?.password)
                User user = User.findByUsername(SecurityContextHolder.getContext().getAuthentication().getName())
                def statusList = statusService.getStatusForTimeline()
                render(view: "home", model: [user : user, statusList: statusList, statusCount: statusList.size()])
            } catch (AuthenticationException) {
                flash.message = "Invalid username or password"
                redirect(uri: "/")
            }
        } else {
            User user = User.findByUsername(userService.springSecurityService.getCurrentUser())
            def statusList = statusService.getStatusForTimeline()
            render(view: "home", model: [user : user, statusList: statusList, statusCount: statusList.size()])
        }
    }

    /**
     * Homepage of the user page after the adding of status
     * @return homepage of the user
     */
    def reload() {
        User user = User.findByUsername(userService.springSecurityService.getCurrentUser())
        def statusList = statusService.getStatusForTimeline()
        render(view: "home", model: [user : user, statusList: statusList, statusCount: statusList.size()])
    }

    /**
     * Logout the user
     * @return landing page
     */
    def logout() {
        userService.logout(request, response)
        redirect(uri : "/")
    }

    /**
     * Save the instance of a user
     * @param userInstance : user to save
     * @return edition form for a user
     */
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance = userDaoService.create(userInstance)
        String url = createLink([action: "activateAccount", absolute: true]).toString()
        userService.contactUser(userInstance.email, userInstance.username, url)

        render (view: "successCreation", model: [username: userInstance.username, type:"success"])
    }

    /**
     * Update an user
     * @param userInstance: user to uodate
     * @param page: page to show
     * @return the page to show
     */
    @Secured(["ROLE_USER","ROLE_ADMIN"])
    def update(User userInstance,String page) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:page
            return
        }

        userInstance = userDaoService.update(userInstance)

        redirect(action: page)
    }

    /**
     * Delete an user
     * @param userInstance : user to delete
     * @return message of deletion
     */
    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    /**
     * Error page, not found
     */
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    /**
     * Follow an user
     * @param user : user to follow
     * @return page of the user
     */
    def followUser(User user) {
        def follow = userDaoService.followUser(springSecurityService.currentUser, user)
        redirect(action: "show", params: params)
    }

    /**
     * Unfollow an user
     * @param user : user to unfollow
     * @return page of the user
     */
    def unfollowUser(User user) {
        userDaoService.unfollowUser(springSecurityService.currentUser, user)
        redirect(action: "show", params: params)
    }

    /**
     * Show the followers of an user
     * @return list of followers
     */
    def showFollowers() {
        def user = springSecurityService.currentUser
        def followersList = userDaoService.findAllFollowersForUser(user)
        render (view: "home", model: [user: user, followersList: followersList])
    }

    /**
     * Show users followed by user
     * @return list of followed
     */
    def showFollowed() {
        def user = springSecurityService.currentUser
        def followedList = userDaoService.findAllFollowedForUser(user)
        render (view: "home", model: [user: user, followedList: followedList])
    }

    /**
     *
     * @param s
     * @return
     */
    def light(Status s) {
        lightService.lightAStatus(springSecurityService.currentUser, s)
        redirect action: 'home', controller: 'user', namespace: null
    }

    /**
     *
     * @param s
     * @return
     */
    def unlight(Status s) {
        lightService.unlightAStatus(springSecurityService.currentUser, s)
        redirect action: 'home', controller: 'user', namespace: null
    }

}

grails-app/views/user/_avatar.gsp
<g:if test="${userInstance.urlAvatar != null}">
    <img src="${userInstance.urlAvatar}" data-holder-rendered="true" style="width: ${width}; display:inline-block !important;">
</g:if>

grails-app/views/user/_form.gsp
<%@ page import="bandstorm.User" %>



<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="user.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="username" required="" value="${userInstance?.username}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="user.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="email" required="" value="${userInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'firstName', 'error')} required">
	<label for="firstName">
		<g:message code="user.firstName.label" default="First Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="firstName" required="" value="${userInstance?.firstName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="user.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" required="" value="${userInstance?.lastName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'country', 'error')} required">
	<label for="country">
		<g:message code="user.country.label" default="Country" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="country" required="" value="${userInstance?.country}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'birthDate', 'error')} required">
	<label for="birthDate">
		<g:message code="user.birthDate.label" default="Birth Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="birthDate" precision="day"  value="${userInstance?.birthDate}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'posts', 'error')} ">
	<label for="posts">
		<g:message code="user.posts.label" default="Posts" />
		
	</label>
	<g:select name="posts" from="${bandstorm.Status.list()}" multiple="multiple" optionKey="id" size="5" value="${userInstance?.posts*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'interests', 'error')} ">
	<label for="interests">
		<g:message code="user.interests.label" default="Interests" />
		
	</label>
	<g:select name="interests" from="${bandstorm.Tag.list()}" multiple="multiple" optionKey="id" size="5" value="${userInstance?.interests*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'participates', 'error')} ">
	<label for="participates">
		<g:message code="user.participates.label" default="Participates" />
		
	</label>
	<g:select name="participates" from="${bandstorm.Event.list()}" multiple="multiple" optionKey="id" size="5" value="${userInstance?.participates*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'manages', 'error')} ">
	<label for="manages">
		<g:message code="user.manages.label" default="Manages" />
		
	</label>
	<g:select name="manages" from="${bandstorm.Event.list()}" multiple="multiple" optionKey="id" size="5" value="${userInstance?.manages*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'groupsFollowed', 'error')} ">
	<label for="groupsFollowed">
		<g:message code="user.groupsFollowed.label" default="Groups Followed" />
		
	</label>
	<g:select name="groupsFollowed" from="${bandstorm.Band.list()}" multiple="multiple" optionKey="id" size="5" value="${userInstance?.groupsFollowed*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="user.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="password" required="" value="${userInstance?.password}"/>

</div>

grails-app/views/user/create.gsp
<%@ page import="bandstorm.User" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<meta name="layout" content="main"/>


<div class="container" style="padding-top: 100px;">

	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-6" >

			<h2 style="color:white;"> Etape 1/2 : Présente toi</h2>

			<g:form url="[resource:userInstance, action:'save']" >
				<g:textField class="form-control ${hasErrors(bean:userInstance,field:'username','errors')}" placeholder="Pseudo" name="username" value="${userInstance.username}">  </g:textField><bR>

                <g:textField class="form-control ${hasErrors(bean:userInstance,field:'email','errors')}"   placeholder="Email" name="email" value="${userInstance.email}">  </g:textField><bR>

                <g:passwordField class="form-control ${hasErrors(bean:userInstance,field:'password','errors')}"  placeholder="Mot de passe" name="password" value="${userInstance.password}">  </g:passwordField><bR>

				<g:textField class="form-control ${hasErrors(bean:userInstance,field:'firstName','errors')}"  placeholder="Prenom" name="firstName" value="${userInstance.firstName}">  </g:textField><bR>
				<g:textField class="form-control ${hasErrors(bean:userInstance,field:'lastName','errors')}"  placeholder="Nom" name="lastName" value="${userInstance.lastName}">  </g:textField><bR>
                <g:textField class="form-control ${hasErrors(bean:userInstance,field:'country','errors')}"  placeholder="Votre pays" name="country" value="${userInstance.country}">  </g:textField><bR>
                <strong style="color:white;">Date de naissance :</strong>
                <g:datePicker class="form-control ${hasErrors(bean:userInstance,field:'birthDate','errors')}" name="birthDate" precision="day"  value="${userInstance?.birthDate}"  /><bR><bR>


				<div style="text-align: right">
					<g:submitButton name="create" class="btn btn-success" action="save" value="Suivant" />
				</div>

			</g:form>


		</div>
	</div>
</div>

grails-app/views/user/home.gsp
<%@ page import="bandstorm.User" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<meta name="layout" content="main"/>


<div class="container" style="padding-top: 100px;">

    <div class="container">

        <div class="row">

            <div class="col-sm-8 blog-main">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <g:form url="[resource: statusInstance, controller: 'status', action: 'save']"
                                name="statusForm">

                            <g:textField id="contentField"
                                         class="form-control ${hasErrors(bean: statusInstance, field: 'content', 'errors')}"
                                         placeholder="Partagez votre actualité." name="content"
                                         value="${statusInstance?.content}" style="height:60px;"></g:textField><bR>

                            <g:textField id="urlField"
                                         class="form-control ${hasErrors(bean: statusInstance, field: 'url', 'errors')}"
                                         placeholder="Un lien à partager ?" name="url" value="${statusInstance?.url}"
                                         style="height:30px;"></g:textField><bR>

                            <g:hiddenField name="lightCount" value="${statusInstance?.lightCount = 0}"/>
                            <div style="text-align: right">
                                <g:submitButton name="publish" class="btn btn-success" action="save"
                                                controller="status" value="Publier" onClick="clearFields()"/>
                            </div>


                            <g:javascript>
                                function clearFields() {

                                    if (document.getElementById("contentField").value != "") {
                                        $("#contentField").fadeOut(500);
                                        $("#contentField").fadeIn(500);
                                    }

                                    if (document.getElementById("urlField").value != "") {
                                        $("#urlField").fadeOut(500);
                                        $("#urlField").fadeIn(500);
                                    }

                                    setTimeout(function () {
                                        document.getElementById("contentField").value = "";
                                        document.getElementById("urlField").value = "";
                                    }, 300);
                                }

                                $(document).ready(function () {

                                    var mypage = 1;
                                    var inLoad = true;

                                    var deviceAgent = navigator.userAgent.toLowerCase();
                                    var agentID = deviceAgent.match(/(iphone|ipod|ipad)/);
                                    var finish = false;

                                    $.get('../status/connectedUserTimeline', function (data) {
                                        $("#timeline").append(data);
                                    });


                                    $(window).on('scroll', function () {


                                        if ((  ($(window).scrollTop() + $(window).height()) >= $(document).height() - 50
                                                || agentID && ($(window).scrollTop() + $(window).height()) + 150 > $(document).height() ) && inLoad == true && !finish) {
                                            inLoad = false;

                                            $.when($.get("../status/connectedUserTimeline", {page: mypage}) ).then(function (data) {

                                                if (data == "") {
                                                    finish = true;
                                                    $("#loading").hide();
                                                }
                                                else {
                                                    $("#timeline").append(data);
                                                    mypage++;
                                                    inLoad = true;
                                                }
                                            });
                                        }
                                    });


                                });

                            </g:javascript>
                        </g:form>
                    </div>
                </div>

                <div style="background-color:rgb(255,255,255);padding:15px;">

                    <ul class="nav nav-tabs">
                        <li role="presentation" style="width:160px;text-align:center;" id="statusTimeline"><g:link controller="user" action="home">Actualité</g:link></li>
                        <li role="presentation" style="width:160px;text-align:center;" id="followedTimeline"><g:link controller="user" action="showFollowed">Abonnements</g:link></li>
                        <li role="presentation" style="width:160px;text-align:center;" id="followerTimeline"><g:link controller="user" action="showFollowers">Abonnés</g:link></li>
                    </ul>

                    <g:if test="${followersList != null || followedList != null}">

                        <g:if test="${followersList != null}">
                            <g:javascript>$("#followerTimeline").addClass('active');</g:javascript>
                            <g:if test="${followersList != []}">
                                <g:each in="${followersList}" var="follower">
                                    <p style="margin-top: 10px; font-size: large" ><a href="${createLink(action: 'show',controller: 'user', id: follower.id)}">${follower.username}</a></p><hr>
                                </g:each>
                            </g:if>
                            <g:else>
                                <p>Désolé, vous n'avez aucun abonné.</p>
                            </g:else>
                        </g:if>
                        <g:else>
                            <g:javascript>$("#followedTimeline").addClass('active');</g:javascript>
                            <g:if test="${followedList != []}">
                                <g:each in="${followedList}" var="follower">
                                    <p style="margin-top: 10px; font-size: large" ><a href="${createLink(action: 'show',controller: 'user', id: follower.id)}">${follower.username}</a></p><hr>
                                </g:each>
                            </g:if>
                            <g:else>
                                <p>Désolé, vous n'avez aucun abonnement.</p>
                            </g:else>
                        </g:else>
                     </g:if>
                    <g:else>
                        <g:javascript>$("#statusTimeline").addClass('active');</g:javascript>
                        <br>
                        <div id="timeline"> </div>
                        <div id="loading" style="text-align: center;"><img src="${resource(dir:"images",file:"loading.gif")}"></div>
                    </g:else>
                </div><!-- /.blog-userHomePage -->
            </div><!-- /.blog-userHomePage -->

            <div class="col-sm-3  blog-sidebar" style="background-color:rgb(255,255,255);padding:15px;">
                <div class="sidebar-module sidebar-module-inset">
                    <g:render template="../user/avatar" model="[userInstance: user, width: '200px']"/>

                    <h4>Crazy <g:fieldValue bean="${user}" field="username"/></h4>

                    <p><em>"Merry"</em> Christmas, May the season be fun joyful and especialy crazy!! :P<br><br>

                    </p>

                </div>

                <div class="sidebar-module">
                    <h4>Ses groupes</h4>
                    <ol class="list-unstyled">
                        <g:each in="${user.getBands()}" var="b">
                            <li><a href="${createLink(action: 'show',controller: 'band', id: b.id)}">${b.name}</a></li>
                        </g:each>
                    </ol>
                </div>
                <bR>

                <div class="sidebar-module">
                </div>
            </div><!-- /.blog-sidebar -->

        </div><!-- /.row -->

    </div>

</div>

</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="bandstorm.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="username" title="${message(code: 'user.username.label', default: 'Username')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'user.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="firstName" title="${message(code: 'user.firstName.label', default: 'First Name')}" />
					
						<g:sortableColumn property="lastName" title="${message(code: 'user.lastName.label', default: 'Last Name')}" />
					
						<g:sortableColumn property="country" title="${message(code: 'user.country.label', default: 'Country')}" />
					
						<g:sortableColumn property="birthDate" title="${message(code: 'user.birthDate.label', default: 'Birth Date')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${userInstanceList}" status="i" var="userInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "username")}</g:link></td>
					
						<td>${fieldValue(bean: userInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "firstName")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "lastName")}</td>
					
						<td>${fieldValue(bean: userInstance, field: "country")}</td>
					
						<td><g:formatDate date="${userInstance.birthDate}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${userInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/user/passwordSettings.gsp
<%@ page import="bandstorm.User" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<meta name="layout" content="main"/>



<div class="container" style="padding-top: 50px;">

    <g:form url="[resource:userInstance, action:'update']" >

    <g:hiddenField name="page" value="passwordSettings"></g:hiddenField>

    <div class="row">

        <h2 style="color: white;"> Bienvenue ${userInstance.username}</h2>
        <br>
        <div class="col-xs-2">

            <ul class="nav nav-pills nav-stacked nav-pills-stacked-example">
                <li role="presentation" ><a href="<g:createLink controller="user" action="profilSettings"/>">Profile</a></li>
                <li role="presentation" class="active"><a href="<g:createLink controller="user" action="passwordSettings"/>">Mot de passe</a></li>
            </ul>



        </div>
        <div class="col-xs-6" >
                <strong style="color:white;">Mot de passe :</strong><br>

                <g:passwordField placeholder="Nouveau mot de passe"  class="form-control ${hasErrors(bean:userInstance,field:'password','errors')}"  name="password" value="">  </g:passwordField>
                <br>
                <div style="text-align: right">
                    <g:submitButton name="create" class="btn btn-success" value="Enregistrer" />
                </div>


        </div>
    </div>

    </g:form>
</div>

grails-app/views/user/successCreation.gsp
<%@ page import="bandstorm.User" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<meta name="layout" content="secondary"/>



<div class="container" style="margin-top: 60px;">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 list-group" style="padding-right: 0px; text-align: center ; background-color: whitesmoke; border: grey 2px solid; border-radius: 5px;">
            <g:if test="${type == 'success'}">
                <p class="list-group-item">Please check you email inbox for activation link</p>
            </g:if>
            <g:else>
                <a class="list-group-item" href="<g:createLink uri="/"/>"><strong>your account has been activated.</strong></a>
                <p>Click to access log in page.</p>
            </g:else>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>