grails-app/domain/bandstorm/Event.groovy
package bandstorm

/**
 * Represent the event an user can organize or participate to.
 * Basically, for the first version of the product an event is a Concert or Festival.
 * In the future we can imagine event to also be a collaborative music project development
 * or crowdfunding musical projects and so on. */

class Event {

    String name
    Date dateCreated
    String address
    String description
    Date dateEvent

    static hasMany = [tags : Tag]

    static constraints = {
        name blank: false, maxSize: 35, minSize: 3
        address maxSize: 200, minSize: 10, blank: false
        description minSize: 2, blank: false
        tags nullable: true
        dateEvent blank: false, validator: {val, obj ->
            return val.after(new Date())
        }
    }
}

grails-app/controllers/bandstorm/EventController.groovy
package bandstorm

import bandstorm.service.dao.EventDAOService
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

import java.text.SimpleDateFormat

import static org.springframework.http.HttpStatus.NOT_FOUND
import static org.springframework.http.HttpStatus.NO_CONTENT

/**
 * Event controller class
 */
@Secured(["ROLE_USER","ROLE_ADMIN"])
@Transactional(readOnly = true)
class EventController {

    EventDAOService eventDAOService

    static allowedMethods = [save: "POST", update: "PUT", delete: "POST"]

    /**
     * Show the list of user's events
     * @param max : max displayed events by page
     * @return the list of events
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.sort = "id"
        params.order = "desc"
        def calendar = Calendar.getInstance()
        calendar.set(2015,Calendar.SEPTEMBER, 01)
        Event event = new Event(name: "",dateEvent: calendar.getTime() ,description: "", address: "")
        respond Event.list(params), model: [eventInstance: event,eventInstanceCount: Event.count()]
    }

    /**
     * Show details of an event
     * @param eventInstance : event to show
     * @return details for event
     */
    def show(Event eventInstance) {
        if(eventInstance == null) {
            return response.sendError(404)
        }

        respond eventInstance
    }

    /**
     * Create an event
     * @return new event
     */
    def create() {
        respond new Event(params)
    }

    /**
     * Save an event instance
     * @param eventInstance : event to save
     * @return event form
     */
    @Transactional
    def save(Event eventInstance) {
        if (eventInstance == null) {
            notFound()
            return
        }

        try {
            eventInstance.name = params.evName
            eventInstance.address = params.evAddress
            eventInstance.description = params.evDescription
            eventInstance.dateEvent = new SimpleDateFormat("dd.MM.yyyy").parse(params.evDate?.replaceAll('/','.'))
            eventInstance.validate()
        } catch (Exception e) {
            e.printStackTrace()
            render template: 'form', model: [eventInstance:eventInstance, status: "KO"]
        }

        if (eventInstance.hasErrors()) {
            render template: 'form', model: [eventInstance:eventInstance, status: "KO"]
            return
        }

        try {
            if(params.evTags) {
                def paramTags = params.evTags.tokenize(';')
                eventInstance.tags = new ArrayList<Tag>()
                paramTags.eachWithIndex { item, index ->
                    def tag = new Tag(name: item).save()
                    eventInstance.tags.add(tag)
            }
            }
        } catch (Exception e) {
            e.printStackTrace()
        }
        eventDAOService.create(eventInstance)
        render template: 'form', model: [eventInstance:eventInstance, status: "OK"]
    }

    /**
     * Edit an event
     * @param eventInstance : event to edit
     * @return an event
     */
    def edit(Event eventInstance) {
        respond eventInstance
    }

    /**
     * Update an event
     * @param eventInstance : event to update
     * @return edition form for event
     */
    @Transactional
    def update(Event eventInstance) {
        if (eventInstance == null) {
            notFound()
            return
        }

        if (eventInstance.hasErrors()) {
            respond eventInstance.errors, view: 'edit'
            return
        }

        eventDAOService.update(eventInstance)
    }

    /**
     * Delete an event
     * @param eventInstance : event to delete
     * @return page to confirm the deletion
     */
    @Transactional
    def delete(Event eventInstance) {

        if (eventInstance == null) {
            if(params.id) {
                eventInstance = Event.get(params.id)
            } else {
                notFound()
                return
            }
        }

        eventDAOService.delete(eventInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Event.label', default: 'Event'), eventInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    /**
     * Error page, not found
     */
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'event.label', default: 'Event'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/event/_display-event.gsp
<g:form action='delete' method="post">
    <dl class="dl-horizontal">
        <g:hiddenField name="id" value="${eventInstance?.id}"/>
        <g:if test="${eventInstance?.name}">
            <dt>Nom</dt>
            <dd><g:fieldValue bean="${eventInstance}" field="name"/>
                <a href="#" id="buttonTrigger">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
                <g:submitButton style="display: none;" name="submit" id="submit"/>
                <g:javascript>
                    $("#buttonTrigger").on( "click", function() {
                        $("#submit").click();
                    });
                </g:javascript>
            </dd>
        </g:if>

        <g:if test="${eventInstance?.dateEvent}">
            <dt>Date de l'évènement</dt>
            <dd><g:fieldValue bean="${eventInstance}" field="dateEvent"/></dd>
        </g:if>

        <g:if test="${eventInstance?.dateCreated}">
            <dt>Date de création</dt>
            <dd><g:fieldValue bean="${eventInstance}" field="dateCreated"/></dd>
        </g:if>

        <g:if test="${eventInstance?.address}">
            <dt>Adresse</dt>
            <dd><g:fieldValue bean="${eventInstance}" field="address"/></dd>
        </g:if>

        <g:if test="${eventInstance?.description}">
            <dt>Description</dt>
            <dd><g:fieldValue bean="${eventInstance}" field="description"/></dd>
        </g:if>

        <g:if test="${eventInstance?.tags}">
            <dt>Tags</dt>
            <dd><g:each in="${eventInstance.tags}" var="tag">
                <span class="label label-default">${tag.name}</span>
            </g:each></dd>
        </g:if>
    </dl>
</g:form>

grails-app/views/event/_form.gsp
<%@ page import="bandstorm.Event" %>

<div class="form-group">
	<div class="row">
		<div class="col-md-6">
			<label for="EventName">Nom</label>
			<g:textField name="evName" class="form-control" maxlength="35" id="EventName" placeholder="Nom"
						 value="${eventInstance?.name}"/>
			<g:hasErrors bean="${eventInstance}" field="name">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<strong>Le nom doit être compris entre 3 et 35 caractères</strong>
				</div>
			</g:hasErrors>
		</div>

		<div class="col-md-6">
			<label for="EventDate">Date de l'évènement</label>
			<g:textField class="form-control" id="EventDate" name="evDate" value="${eventInstance.dateEvent.format('dd/MM/yyyy')}" placeholder="DD/MM/YYYY"/>
			<g:hasErrors bean="${eventInstance}" field="dateEvent">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
							aria-hidden="true">&times;</span></button>
					<strong>Vous devez indiquer une date postérieure à aujourd'hui au format DD/MM/YYYY</strong>
				</div>
			</g:hasErrors>
		</div>
	</div>
</div>

<div class="form-group">
	<label for="eventAddress">Adresse</label>
	<g:textField name="evAddress" class="form-control"
				 maxlength="200" id="eventAddress" placeholder="Adresse" value="${eventInstance?.address}"/>
	<g:hasErrors bean="${eventInstance}" field="address">

		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
					aria-hidden="true">&times;</span></button>
			<strong>Indiquez une adresse (entre 10 et 200 caractères)</strong>
		</div>
	</g:hasErrors>
</div>

<div class="form-group">
	<label for="eventDescription">Description</label>
	<g:textArea rows="5" name="evDescription" class="form-control" id="eventDescription" placeholder="Décrivez votre évènement" value="${eventInstance?.description}"/>
	<g:hasErrors bean="${eventInstance}" field="description">
		<div class="alert alert-danger alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
					aria-hidden="true">&times;</span></button>
			<strong>Donnez une description</strong>
		</div>
	</g:hasErrors>
</div>

<div class="form-group">
	<label for="eventTags">Tags</label>
	<g:textField name="evTags" class="form-control" id="eventTags" placeholder="Ajoutez des tags en les séparant par un point-virgule"/>
</div>

<div>
	<h1 style="display: none" id="head">${(status) ? status :'empty'}</h1>
</div>

<g:submitToRemote class="btn btn-primary" url="[resource:eventInstance, controller:'event', action:'save']" update="creationForm" onSuccess="if(document.getElementById('head').innerHTML == 'OK'){swal({title:'Succès !',text: 'Votr évènement a bien été créée !',type: 'success'},function(){window.location.href = '${createLink(action: 'index')}';});}" value="Créer" />

grails-app/views/event/_modal.gsp
<!-- Modal -->
<div class="modal fade" id="myModal${status}" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Détail</h4>
            </div>
            <div class="modal-body">
                <g:render template="/event/display-event" model="[eventInstance: eventInstance]"></g:render>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

grails-app/views/event/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-event" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${eventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${eventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:eventInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/event/edit.gsp
<%@ page import="bandstorm.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-event" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-event" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${eventInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${eventInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:eventInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${eventInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/event/index.gsp
<%@ page import="bandstorm.Event" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'event.label', default: 'Event')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
        <style>
            .centered ul li {
                display: inline;
                margin: 3px;
            }
            .pagination {
                margin: 2px;
                box-sizing: border-box;
            }

            .prev, .next {
                border: solid 2px deepskyblue;
                background: whitesmoke;
                border-radius: 5px;
                padding: 4px;
                box-sizing: inherit;
            }
            
            .next {
                padding: 4.5px 10px 4.5px 10px;
            }

            .centered ul a {
                color: black;
                box-sizing: inherit;
            }

            .centered ul a:hover {
                text-decoration: none;
            }

            .alert {
                margin-top: 5px;
            }

            .tab-content {
                background-color: whitesmoke;
                padding: 10px;
                padding-top:30px ;
                margin-bottom: 30px;
            }
        </style>
	</head>
	<body>
		<div class="container centered" style=" padding-top:30px;width: 90%; min-height: 300px; background-color: rgba(245,245,245,0.95);">
            <div class="container-fluid">
                <h2>Mes Événements</h2>
                <ul class="nav nav-tabs nav-justified">
                    <li class="active"><a data-toggle="tab" href="#view">Liste d'évènements</a></li>
                    <li><a data-toggle="tab" href="#create">Créer un nouvel évènement</a></li>
                </ul>

                <div class="tab-content">
                    <div id="view" class="tab-pane fade in active">
                        <div class="table-responsive" id="listedEvents">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Nom</th>
                                    <th>Date de l'évènement</th>
                                    <th>Date de création</th>
                                    <th>Adresse</th>
                                    <th>Description</th>
                                </tr>
                                </thead>
                                <tbody>
                                <g:each in="${eventInstanceList}" var="eventInstance" status="i">
                                    <tr>
                                        <td><a type="button" data-toggle="modal" data-target="#myModal${i}">${fieldValue(bean: eventInstance, field: "name")}</a></td>
                                        <g:render template="/event/modal" model="[eventInstance: eventInstance, status:i]"></g:render>

                                        <td><g:formatDate date="${eventInstance.dateEvent}"/></td>

                                        <td><g:formatDate date="${eventInstance.dateCreated}" /></td>

                                        <td>${fieldValue(bean: eventInstance, field: "address")}</td>

                                        <td>${fieldValue(bean: eventInstance, field: "description")}</td>
                                    </tr>
                                </g:each>
                                </tbody>
                            </table>

                            <g:paginate total="${eventInstanceCount}" />

                        </div>
                    </div>
                    <div id="create" class="tab-pane fade">
                        <g:form >
                            <fieldset class="form" id="creationForm">
                                <g:render template="form" bean="${eventInstance}"/>
                            </fieldset>
                        </g:form>
                    </div>
                </div>
            </div>
		</div>
	</body>
</html>

grails-app/views/event/show.gsp
<%@ page import="bandstorm.Event" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<meta name="layout" content="main"/>



<div class="container" style="padding-top: 100px;">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 blog-main" style="background-color:rgb(255,255,255);padding:15px;margin-left: 10px;">
				<h2>${eventInstance?.name}</h2>
				<br>
				<div class="bs-example" data-example-id="media-alignment">
					<g:render template="/event/display-event" model="[eventInstance:eventInstance]"></g:render>
				</div>
			</div><!-- /.blog-userHomePage -->
		</div><!-- /.row -->
	</div>
</div>

</body>
</html>